# Generated by Django 5.1.7 on 2025-03-29 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_item_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PFUser',
            fields=[
                ('userID', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('memberID', models.CharField(max_length=255)),
                ('gymAbbr', models.CharField(max_length=10)),
                ('gymCity', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('firstName', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('dob', models.CharField(max_length=255)),
                ('phoneNum', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=50)),
                ('termsAccepted', models.BooleanField()),
                ('dateJoined', models.DateField()),
                ('activeAccnt', models.BooleanField()),
                ('gymState', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'PFUsers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlanetFitnessDB',
            fields=[
                ('databaseID', models.AutoField(primary_key=True, serialize=False)),
                ('memberID', models.CharField(max_length=255)),
                ('gymAbbr', models.CharField(max_length=10)),
                ('gymCity', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('firstName', models.CharField(max_length=255)),
                ('uploadDate', models.DateTimeField()),
                ('gymState', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'PlanetFitnessDB',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
