# Generated by Django 5.1.7 on 2025-04-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_pfuser_planetfitnessdb_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffilGyms',
            fields=[
                ('gymID', models.BigAutoField(primary_key=True, serialize=False)),
                ('gymName', models.CharField(max_length=255)),
                ('gymCity', models.CharField(max_length=255)),
                ('gymState', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'AffilGyms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LifetimeFitnessDB',
            fields=[
                ('databaseID', models.AutoField(primary_key=True, serialize=False)),
                ('gymCity', models.CharField(max_length=255)),
                ('gymAbbr', models.CharField(max_length=10)),
                ('memberID', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('firstName', models.CharField(max_length=255)),
                ('uploadDate', models.DateTimeField()),
                ('gymState', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'LifetimeFitnessDB',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LTFUsers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('userID', models.UUIDField()),
                ('memberID', models.CharField(max_length=15)),
                ('gymAbbr', models.CharField(max_length=5)),
                ('gymCity', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('firstName', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('birthDate', models.CharField(max_length=10)),
                ('phoneNum', models.CharField(max_length=12)),
                ('gender', models.CharField(max_length=10)),
                ('termsAccepted', models.BooleanField(default=False)),
                ('dateJoined', models.DateField(auto_now_add=True)),
                ('activeAccnt', models.BooleanField(default=True)),
                ('gymState', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'LTFUsers',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PFUsers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('userID', models.UUIDField()),
                ('memberID', models.CharField(max_length=15)),
                ('gymAbbr', models.CharField(max_length=5)),
                ('gymCity', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('firstName', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('birthDate', models.CharField(max_length=10)),
                ('phoneNum', models.CharField(max_length=12)),
                ('gender', models.CharField(max_length=10)),
                ('termsAccepted', models.BooleanField(default=False)),
                ('dateJoined', models.DateField(auto_now_add=True)),
                ('activeAccnt', models.BooleanField(default=True)),
                ('gymState', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'PFUsers',
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='PFUser',
        ),
    ]
